"""Adicionado campo photos à tabela property

Revision ID: 1682255f9ee7
Revises: 
Create Date: 2025-02-13 18:26:15.947085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1682255f9ee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photos', sa.String(length=500), nullable=True))

    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('photos')

    # ### end Alembic commands ###
